# Generated by Django 5.0.4 on 2024-06-16 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_rename_bid_amount_bid_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-amount']},
        ),
    ]
