# Generated by Django 5.0.4 on 2024-06-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='posted_date',
            field=models.DateTimeField(),
        ),
    ]
