# Generated by Django 5.0.4 on 2024-06-11 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
