# Generated by Django 5.0.4 on 2024-06-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehicle_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='posted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
