# Generated by Django 5.0.4 on 2024-06-15 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_alter_vehicle_posted_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='abs_breaks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='airbags',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='alloy_wheels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(choices=[('motorbike', 'Motorbike'), ('car', 'Car'), ('three_wheeler', 'Three Wheeler'), ('bicycle', 'Bicycle'), ('lorry', 'Lorry'), ('truck', 'Truck'), ('van', 'Van'), ('bus', 'Bus'), ('coupe', 'Coupe'), ('suv', 'SUV (Sport Utility Vehicle)'), ('tractor', 'Tractor'), ('atv', 'ATV (All-Terrain Vehicle)'), ('sedan', 'Sedan'), ('limousine', 'Limousine'), ('electric_vehicle', 'Electric Vehicle'), ('hybrid_vehicle', 'Hybrid Vehicle'), ('offroad_vehicle', 'Off-Road Vehicle'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='central_locking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_capacity',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_type',
            field=models.CharField(choices=[('electric', 'Electric'), ('hybrid', 'Hybrid'), ('ice', 'ICE (Internal Combustion Engine)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='leather_seats',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Chevrolet', 'Chevrolet'), ('Ferrari', 'Ferrari'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Jaguar', 'Jaguar'), ('Kia', 'Kia'), ('Lamborghini', 'Lamborghini'), ('Mahindra', 'Mahindra'), ('Mazda', 'Mazda'), ('McLaren', 'McLaren'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Peugeot', 'Peugeot'), ('Perodua', 'Perodua'), ('Porsche', 'Porsche'), ('Renault', 'Renault'), ('Rolls-Royce', 'Rolls-Royce'), ('Suzuki', 'Suzuki'), ('Tata Motors', 'Tata Motors'), ('Tesla', 'Tesla'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='no_of_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_pictures/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_pictures/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='power_steering',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='power_windows',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='reverse_camera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='sunroof',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission_type',
            field=models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], max_length=10, null=True),
        ),
    ]
