# Generated by Django 5.0.4 on 2024-06-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_vehicle_color_vehicle_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(choices=[('motorbike', 'Motorbike'), ('car', 'Car'), ('three_wheeler', 'Three Wheeler'), ('bicycle', 'Bicycle'), ('lorry', 'Lorry'), ('truck', 'Truck'), ('van', 'Van'), ('bus', 'Bus'), ('coupe', 'Coupe'), ('suv', 'SUV (Sport Utility Vehicle)'), ('tractor', 'Tractor'), ('atv', 'ATV (All-Terrain Vehicle)'), ('sedan', 'Sedan'), ('limousine', 'Limousine'), ('electric_vehicle', 'Electric Vehicle'), ('hybrid_vehicle', 'Hybrid Vehicle'), ('offroad_vehicle', 'Off-Road Vehicle'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_capacity',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_type',
            field=models.CharField(choices=[('electric', 'Electric'), ('hybrid', 'Hybrid'), ('ice', 'ICE (Internal Combustion Engine)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.CharField(choices=[('Audi', 'Audi'), ('BMW', 'BMW'), ('Chevrolet', 'Chevrolet'), ('Ferrari', 'Ferrari'), ('Ford', 'Ford'), ('Honda', 'Honda'), ('Hyundai', 'Hyundai'), ('Jaguar', 'Jaguar'), ('Kia', 'Kia'), ('Lamborghini', 'Lamborghini'), ('Mahindra', 'Mahindra'), ('Mazda', 'Mazda'), ('McLaren', 'McLaren'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Peugeot', 'Peugeot'), ('Perodua', 'Perodua'), ('Porsche', 'Porsche'), ('Renault', 'Renault'), ('Rolls-Royce', 'Rolls-Royce'), ('Suzuki', 'Suzuki'), ('Tata Motors', 'Tata Motors'), ('Tesla', 'Tesla'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='no_of_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission_type',
            field=models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], max_length=10, null=True),
        ),
    ]
