# Generated by Django 5.0.4 on 2024-06-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_vehicle_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='engine_type',
            field=models.CharField(choices=[('Electric', 'Electric'), ('Hybrid', 'Hybrid'), ('Internal Combustion Engine', 'ICE (Internal Combustion Engine)')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission_type',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=10, null=True),
        ),
    ]
