# Generated by Django 5.0.4 on 2024-06-19 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_vehicle_auction_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='first_bid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
