# Generated by Django 5.0.4 on 2024-06-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_vehicle_first_bid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(choices=[('motorbike', 'Motorbike'), ('car', 'Car'), ('three_wheeler', 'Three Wheeler'), ('lorry', 'Lorry'), ('truck', 'Truck'), ('van', 'Van'), ('bus', 'Bus'), ('coupe', 'Coupe'), ('suv', 'SUV (Sport Utility Vehicle)'), ('tractor', 'Tractor'), ('atv', 'ATV (All-Terrain Vehicle)'), ('sedan', 'Sedan'), ('limousine', 'Limousine'), ('electric_vehicle', 'Electric Vehicle'), ('hybrid_vehicle', 'Hybrid Vehicle'), ('offroad_vehicle', 'Off-Road Vehicle'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
