# Generated by Django 5.0.6 on 2024-06-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userprofile_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_address',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
