# Generated by Django 5.0.6 on 2024-06-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trading_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
