# Generated by Django 5.0.6 on 2024-06-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_trading_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='trading_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
