# Generated by Django 5.0.4 on 2024-06-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_userwatchlistitem_watchlist_delete_watchlistitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='added_at',
        ),
    ]
